// Copyright (c) 2026 MiniStack Contributors. SPDX-License-Identifier: MIT
// Copies or substantial portions, including AI-assisted ports or rewrites, must retain this notice (see LICENSE).
//
// Parity suite: the same SQL runs against a MiniStack DSQL cluster and against
// embedded-dsql, and the outcomes must match. Many cases are taken from
// MiniStack 1.5.9 tests/test_dsql.py. MiniStack's LICENSE is reproduced in
// THIRD_PARTY_NOTICES at the root of this repository.
//
// Run with a MiniStack started with SERVICES=dsql DSQL_STRICT=1 and the Docker
// socket mounted:
//
//	EMBEDDED_DSQL_MINISTACK_URL=http://127.0.0.1:4566 go test -tags parity -run Parity -v .

//go:build parity

package embeddeddsql

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/stretchr/testify/require"
)

// A parity case is a sequence of statements. Placeholders: {{t}} is a table
// prefix unique to the case and protocol, {{last}} the first column of the
// previous statement's first row, and a leading "2:" runs the statement on a
// second connection.
type parityCase struct {
	name       string
	steps      []string
	simpleOnly bool
}

var parityCases = []parityCase{
	// Plain DDL and DML.
	{name: "create insert select", steps: []string{
		"CREATE TABLE {{t}} (id bigint PRIMARY KEY, name text, doc jsonb, at timestamptz, u uuid)",
		"INSERT INTO {{t}} VALUES (1, 'a', '{\"k\": 1}', now(), gen_random_uuid())",
		"SELECT name FROM {{t}} WHERE id = 1",
		"UPDATE {{t}} SET name = 'b' WHERE id = 1",
		"DELETE FROM {{t}} WHERE id = 1",
	}},
	{name: "leading comment", steps: []string{"-- migration\nCREATE TABLE {{t}} (id int)", "/* x */ CREATE EXTENSION pgcrypto"}},
	{name: "create table if not exists", steps: []string{"CREATE TABLE IF NOT EXISTS {{t}} (id int)", "CREATE TABLE IF NOT EXISTS {{t}} (id int)"}},
	{name: "create view", steps: []string{"CREATE TABLE {{t}} (id int)", "CREATE VIEW {{t}}_v AS SELECT id FROM {{t}}"}},
	{name: "language sql function", steps: []string{"CREATE FUNCTION {{t}}_f() RETURNS int LANGUAGE sql AS $$ SELECT 1 $$"}},
	{name: "sequence cache", steps: []string{"CREATE SEQUENCE {{t}}_s CACHE 1", "CREATE SEQUENCE {{t}}_s2 CACHE 100", "CREATE SEQUENCE {{t}}_s3 CACHE 65536"}},
	{name: "schema", steps: []string{"CREATE SCHEMA {{t}}_sc", "CREATE TABLE {{t}}_sc.x (id bigint PRIMARY KEY)"}},

	// Denylist.
	{name: "deny create type", steps: []string{"CREATE TYPE {{t}}_mood AS ENUM ('sad')"}},
	{name: "deny extension", steps: []string{"CREATE EXTENSION pgcrypto"}},
	{name: "deny trigger", steps: []string{"CREATE TRIGGER trg AFTER INSERT ON t EXECUTE FUNCTION f()"}},
	{name: "deny temp table", steps: []string{"CREATE TEMP TABLE {{t}} (a int)"}},
	{name: "deny unlogged table", steps: []string{"CREATE UNLOGGED TABLE {{t}} (a int)"}},
	{name: "deny materialized view", steps: []string{"CREATE MATERIALIZED VIEW {{t}}_mv AS SELECT 1"}},
	{name: "deny truncate", steps: []string{"CREATE TABLE {{t}} (id int)", "TRUNCATE {{t}}"}},
	{name: "deny do", steps: []string{"DO $$ BEGIN NULL; END $$"}},
	{name: "deny plpgsql function", steps: []string{"CREATE FUNCTION {{t}}_f() RETURNS int LANGUAGE plpgsql AS $$ BEGIN RETURN 1; END $$"}},
	{name: "deny partitioning", steps: []string{"CREATE TABLE {{t}} (a int) PARTITION BY RANGE (a)"}},
	{name: "deny exclude", steps: []string{"CREATE TABLE {{t}} (a int, EXCLUDE (a WITH =))"}},
	{name: "deny vacuum", steps: []string{"VACUUM"}},
	{name: "deny listen notify", steps: []string{"LISTEN c", "NOTIFY c"}},
	{name: "deny lock", steps: []string{"CREATE TABLE {{t}} (id int)", "LOCK TABLE {{t}} IN ACCESS EXCLUSIVE MODE"}},
	{name: "deny savepoint", steps: []string{"BEGIN", "SAVEPOINT sp", "ROLLBACK"}},
	{name: "deny copy", steps: []string{"CREATE TABLE {{t}} (id int)", "COPY {{t}} TO STDOUT"}},

	// Column types.
	{name: "type serial", steps: []string{"CREATE TABLE {{t}} (id serial)"}},
	{name: "type bigserial", steps: []string{"CREATE TABLE {{t}} (id bigserial)"}},
	{name: "type money", steps: []string{"CREATE TABLE {{t}} (id int, m money)"}},
	{name: "type inet", steps: []string{"CREATE TABLE {{t}} (id int, a inet)"}},
	{name: "type array", steps: []string{"CREATE TABLE {{t}} (id int, a text[])"}},
	{name: "type interval fields", steps: []string{"CREATE TABLE {{t}} (id int, a interval day to second)"}},
	{name: "type interval bogus", steps: []string{"CREATE TABLE {{t}} (id int, a interval foo)"}},
	{name: "type numeric varchar", steps: []string{"CREATE TABLE {{t}} (id int, a numeric(18,6), b varchar(10), c character varying(3))"}},
	{name: "literal does not hide serial", steps: []string{"CREATE TABLE {{t}} (a text DEFAULT 'x;y', b serial)"}},

	// Identity.
	{name: "identity bigint", steps: []string{"CREATE TABLE {{t}} (id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY)"}},
	{name: "identity int", steps: []string{"CREATE TABLE {{t}} (id int GENERATED BY DEFAULT AS IDENTITY (CACHE 1))"}},
	{name: "identity cache 100", steps: []string{"CREATE TABLE {{t}} (id bigint GENERATED ALWAYS AS IDENTITY (CACHE 100))"}},

	// ALTER TABLE subset.
	{name: "alter add column plain", steps: []string{"CREATE TABLE {{t}} (id int)", "ALTER TABLE {{t}} ADD COLUMN c integer", "ALTER TABLE {{t}} ADD COLUMN IF NOT EXISTS d numeric(18,6)"}},
	{name: "alter add column default", steps: []string{"CREATE TABLE {{t}} (id int)", "ALTER TABLE {{t}} ADD COLUMN c int DEFAULT 0"}},
	{name: "alter add column not null", steps: []string{"CREATE TABLE {{t}} (id int)", "ALTER TABLE {{t}} ADD COLUMN c text NOT NULL"}},
	{name: "alter add column collate", steps: []string{"CREATE TABLE {{t}} (id int)", `ALTER TABLE {{t}} ADD COLUMN c text COLLATE "C"`}},
	{name: "alter add column serial", steps: []string{"CREATE TABLE {{t}} (id int)", "ALTER TABLE {{t}} ADD COLUMN c serial"}},
	{name: "alter column type", steps: []string{"CREATE TABLE {{t}} (id int, c int)", "ALTER TABLE {{t}} ALTER COLUMN c TYPE text"}},
	{name: "alter set not null", steps: []string{"CREATE TABLE {{t}} (id int, c int)", "ALTER TABLE {{t}} ALTER COLUMN c SET NOT NULL"}},
	{name: "alter drop not null and defaults", steps: []string{"CREATE TABLE {{t}} (id int, c int NOT NULL)", "ALTER TABLE {{t}} ALTER COLUMN c DROP NOT NULL", "ALTER TABLE {{t}} ALTER COLUMN c SET DEFAULT 0", "ALTER TABLE {{t}} ALTER COLUMN c DROP DEFAULT"}},
	{name: "alter add primary key", steps: []string{"CREATE TABLE {{t}} (id int)", "ALTER TABLE {{t}} ADD PRIMARY KEY (id)"}},
	{name: "alter add unique", steps: []string{"CREATE TABLE {{t}} (id int)", "ALTER TABLE {{t}} ADD CONSTRAINT u UNIQUE (id)"}},
	{name: "alter add check", steps: []string{"CREATE TABLE {{t}} (id int)", "ALTER TABLE {{t}} ADD CONSTRAINT c CHECK (id > 0)", "ALTER TABLE {{t}} ADD CONSTRAINT c2 CHECK (id > 0) NOT VALID"}},
	{name: "alter rename", steps: []string{"CREATE TABLE {{t}} (id int)", "ALTER TABLE {{t}} RENAME COLUMN id TO id2", "ALTER TABLE {{t}} RENAME TO {{t}}_r"}},
	{name: "alter drop column", steps: []string{"CREATE TABLE {{t}} (id int PRIMARY KEY, x int, y int)", "ALTER TABLE {{t}} DROP COLUMN x", "ALTER TABLE {{t}} DROP COLUMN y, DROP COLUMN id"}},
	{name: "alter drop pk column", steps: []string{"CREATE TABLE {{t}} (id int PRIMARY KEY, x int)", "ALTER TABLE {{t}} DROP COLUMN id"}},
	{name: "alter drop composite pk column", steps: []string{"CREATE TABLE {{t}} (a int, b int, c int, PRIMARY KEY (a, b))", "ALTER TABLE {{t}} DROP COLUMN b"}},
	{name: "alter drop column no pk", steps: []string{"CREATE TABLE {{t}} (a int, b int)", "ALTER TABLE {{t}} DROP COLUMN a"}},
	{name: "alter drop column unknown table", steps: []string{"ALTER TABLE {{t}}_missing DROP COLUMN a"}},
	{name: "alter identity cache", steps: []string{"CREATE TABLE {{t}} (id bigint NOT NULL)", "ALTER TABLE {{t}} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY", "ALTER TABLE {{t}} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (CACHE 1)"}},

	// Foreign keys and DEFERRABLE.
	{name: "foreign key inline", steps: []string{"CREATE TABLE {{t}}_p (id bigint PRIMARY KEY)", "CREATE TABLE {{t}}_c (id bigint PRIMARY KEY, p bigint REFERENCES {{t}}_p ON DELETE CASCADE)"}},
	{name: "foreign key alter needs not valid", steps: []string{"CREATE TABLE {{t}}_p (id bigint PRIMARY KEY)", "CREATE TABLE {{t}}_c (id bigint, p bigint)", "ALTER TABLE {{t}}_c ADD CONSTRAINT fk FOREIGN KEY (p) REFERENCES {{t}}_p", "ALTER TABLE {{t}}_c ADD CONSTRAINT fk FOREIGN KEY (p) REFERENCES {{t}}_p NOT VALID"}},
	{name: "foreign key enforced", steps: []string{"CREATE TABLE {{t}}_p (id bigint PRIMARY KEY)", "CREATE TABLE {{t}}_c (id bigint PRIMARY KEY, p bigint REFERENCES {{t}}_p)", "INSERT INTO {{t}}_c VALUES (1, 42)"}},
	{name: "deferrable unique", steps: []string{"CREATE TABLE {{t}} (a int, UNIQUE (a) DEFERRABLE)"}},
	{name: "deferrable check", steps: []string{"CREATE TABLE {{t}} (a int, CONSTRAINT c CHECK (a > 0) DEFERRABLE INITIALLY IMMEDIATE)"}},
	{name: "not deferrable", steps: []string{"CREATE TABLE {{t}} (a int, UNIQUE (a) NOT DEFERRABLE)"}},
	{name: "deferrable foreign key", steps: []string{"CREATE TABLE {{t}}_p (id int PRIMARY KEY)", "CREATE TABLE {{t}}_c (p int REFERENCES {{t}}_p DEFERRABLE INITIALLY DEFERRED)"}},

	// Indexes.
	{name: "index sync rejected", steps: []string{"CREATE TABLE {{t}} (id int, a int)", "CREATE INDEX {{t}}_i ON {{t}} (a)"}},
	{name: "index concurrently", steps: []string{"CREATE TABLE {{t}} (id int, a int)", "CREATE INDEX CONCURRENTLY {{t}}_i ON {{t}} (a)"}},
	{name: "index using", steps: []string{"CREATE TABLE {{t}} (id int, a int)", "CREATE INDEX ASYNC {{t}}_i ON {{t}} USING btree (a)"}},
	{name: "index where", steps: []string{"CREATE TABLE {{t}} (id int, a int)", "CREATE INDEX ASYNC {{t}}_i ON {{t}} (a) WHERE a > 0"}},
	{name: "index volatile", steps: []string{"CREATE TABLE {{t}} (id int, a int)", "CREATE INDEX ASYNC {{t}}_i ON {{t}} (random())"}},
	{name: "index include expression", steps: []string{"CREATE TABLE {{t}} (id int, a int, b text)", "CREATE INDEX ASYNC {{t}}_i ON {{t}} (a) INCLUDE (lower(b))"}},
	{name: "index nine keys", steps: []string{"CREATE TABLE {{t}} (a int, b int, c int, d int, e int, f int, g int, h int, i int)", "CREATE INDEX ASYNC {{t}}_i ON {{t}} (a,b,c,d,e,f,g,h,i)"}},
	{name: "index if not exists unnamed", steps: []string{"CREATE TABLE {{t}} (a int)", "CREATE INDEX ASYNC IF NOT EXISTS ON {{t}} (a)"}},
	{name: "index async and sys.jobs", steps: []string{
		"CREATE TABLE {{t}} (id bigint PRIMARY KEY, email text)",
		"CREATE INDEX ASYNC {{t}}_email ON {{t}} (email)",
		"SELECT status, job_type, object_name FROM sys.jobs WHERE job_id = '{{last}}'",
		"CREATE INDEX ASYNC ON {{t}} (lower(email))",
		"SELECT sys.wait_for_job('{{last}}')",
		"SELECT indexname FROM pg_indexes WHERE tablename = '{{t}}' ORDER BY indexname",
	}},
	{name: "index async duplicate name", steps: []string{"CREATE TABLE {{t}} (a int)", "CREATE INDEX ASYNC {{t}}_i ON {{t}} (a)", "CREATE INDEX ASYNC {{t}}_i ON {{t}} (a)"}},
	{name: "index async missing table", steps: []string{"CREATE INDEX ASYNC {{t}}_i ON {{t}}_missing (a)"}},
	{name: "unique index async over duplicates fails the job", steps: []string{
		"CREATE TABLE {{t}} (id bigint PRIMARY KEY, email text)",
		"INSERT INTO {{t}} VALUES (1, 'a'), (2, 'a')",
		"CREATE UNIQUE INDEX ASYNC {{t}}_u ON {{t}} (email)",
		"SELECT status FROM sys.jobs WHERE job_id = '{{last}}'",
	}},
	{name: "validate constraint async", steps: []string{
		"CREATE TABLE {{t}} (id int)",
		"ALTER TABLE {{t}} ADD CONSTRAINT pos CHECK (id > 0) NOT VALID",
		"ALTER TABLE ASYNC {{t}} VALIDATE CONSTRAINT pos",
		"SELECT status, job_type FROM sys.jobs WHERE job_id = '{{last}}'",
	}},
	{name: "sys.jobs unknown column", steps: []string{"SELECT nope FROM sys.jobs"}},
	{name: "wait for unknown job", steps: []string{"SELECT sys.wait_for_job('doesnotexist')"}},

	// Locking clauses.
	{name: "for update", steps: []string{"CREATE TABLE {{t}} (id int PRIMARY KEY, v int)", "SELECT v FROM {{t}} WHERE v > 1 FOR UPDATE", "SELECT v FROM {{t}} FOR KEY SHARE"}},
	{name: "for share", steps: []string{"CREATE TABLE {{t}} (id int PRIMARY KEY, v int)", "SELECT v FROM {{t}} FOR SHARE"}},
	{name: "for no key update", steps: []string{"CREATE TABLE {{t}} (id int PRIMARY KEY, v int)", "SELECT v FROM {{t}} FOR NO KEY UPDATE"}},
	{name: "for share in literal", steps: []string{"SELECT 'FOR SHARE' AS s"}},

	// Transactions.
	{name: "two ddl in a transaction", steps: []string{"BEGIN", "CREATE TABLE {{t}}_a (id int)", "CREATE TABLE {{t}}_b (id int)", "ROLLBACK"}},
	{name: "ddl then dml", steps: []string{"CREATE TABLE {{t}} (id int)", "BEGIN", "CREATE TABLE {{t}}_a (id int)", "INSERT INTO {{t}} VALUES (1)", "ROLLBACK"}},
	{name: "dml then ddl", steps: []string{"CREATE TABLE {{t}} (id int)", "BEGIN", "INSERT INTO {{t}} VALUES (1)", "CREATE TABLE {{t}}_a (id int)", "ROLLBACK"}},
	{name: "autocommit sequential ddl", steps: []string{"CREATE TABLE {{t}}_a (id int)", "CREATE TABLE {{t}}_b (id int)", "INSERT INTO {{t}}_a VALUES (1)"}},
	{name: "rejection aborts the block", steps: []string{"CREATE TABLE {{t}} (id int)", "BEGIN", "INSERT INTO {{t}} VALUES (1)", "TRUNCATE {{t}}", "SELECT 1", "COMMIT", "SELECT count(*) FROM {{t}}"}},
	{name: "rollback clears the abort", steps: []string{"BEGIN", "TRUNCATE x", "ROLLBACK", "SELECT 1"}},
	{name: "row limit", steps: []string{"CREATE TABLE {{t}} (id int)", valuesInsertParity(3001), valuesInsertParity(3000)}},
	{name: "cumulative row limit", steps: []string{"CREATE TABLE {{t}} (id int)", "BEGIN", valuesInsertParity(2000), valuesInsertParity(2000), "ROLLBACK"}},
	{name: "stale catalog OC001", steps: []string{
		"CREATE TABLE {{t}} (id int)",
		"BEGIN",
		"SELECT count(*) FROM {{t}}",
		"2:CREATE TABLE {{t}}_other (id int)",
		"SELECT count(*) FROM {{t}}",
		"ROLLBACK",
		"BEGIN",
		"SELECT count(*) FROM {{t}}",
		"COMMIT",
	}},

	{name: "explain analyze is dml", steps: []string{"CREATE TABLE {{t}} (id int)", "BEGIN", "CREATE TABLE {{t}}_a (id int)", "EXPLAIN ANALYZE INSERT INTO {{t}} VALUES (1)", "ROLLBACK"}},
	{name: "cte write is dml", steps: []string{"CREATE TABLE {{t}} (id int)", "BEGIN", "CREATE TABLE {{t}}_a (id int)", "WITH x AS (SELECT 1) INSERT INTO {{t}} SELECT 1", "ROLLBACK"}},
	{name: "24 indexes per table", steps: twentyFiveIndexes()},

	// Multi-statement batches only exist in the simple protocol.
	{name: "batch ddl and dml", simpleOnly: true, steps: []string{"CREATE TABLE {{t}} (id int); INSERT INTO {{t}} VALUES (1)"}},
	{name: "batch two ddl", simpleOnly: true, steps: []string{"CREATE TABLE {{t}}_a (id int); CREATE TABLE {{t}}_b (id int)"}},
	{name: "batch dml", simpleOnly: true, steps: []string{"CREATE TABLE {{t}} (id int)", "INSERT INTO {{t}} VALUES (1); INSERT INTO {{t}} VALUES (2)"}},
	{name: "batch async index", simpleOnly: true, steps: []string{"CREATE TABLE {{t}} (id int)", "SELECT 1; CREATE INDEX ASYNC {{t}}_i ON {{t}} (id)"}},
	{name: "batch explicit transaction", simpleOnly: true, steps: []string{"CREATE TABLE {{t}} (id int)", "BEGIN; INSERT INTO {{t}} VALUES (1); COMMIT"}},
}

func twentyFiveIndexes() []string {
	steps := []string{"CREATE TABLE {{t}} (id bigint PRIMARY KEY, a int)"}
	// The primary key index counts toward the 24.
	for i := 0; i < 24; i++ {
		steps = append(steps, fmt.Sprintf("CREATE INDEX ASYNC {{t}}_i%d ON {{t}} (a)", i))
	}
	return steps
}

func valuesInsertParity(n int) string {
	var b strings.Builder
	b.WriteString("INSERT INTO {{t}} VALUES ")
	for i := 0; i < n; i++ {
		if i > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(&b, "(%d)", i)
	}
	return b.String()
}

const ministackAuth = "AWS4-HMAC-SHA256 Credential=test/20260101/us-east-1/dsql/aws4_request, SignedHeaders=host, Signature=0"

func ministackCall(ctx context.Context, method, endpoint string, body io.Reader) (map[string]any, error) {
	req, err := http.NewRequestWithContext(ctx, method, endpoint, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", ministackAuth)
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	data, readErr := io.ReadAll(resp.Body)
	if err := resp.Body.Close(); err != nil {
		return nil, err
	}
	if readErr != nil {
		return nil, readErr
	}
	if resp.StatusCode/100 != 2 {
		return nil, fmt.Errorf("%s %s: %s: %s", method, endpoint, resp.Status, data)
	}
	out := map[string]any{}
	if err := json.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("decode %s: %w", data, err)
	}
	return out, nil
}

// startMiniStackCluster creates a DSQL cluster on MiniStack and returns its
// DSN; the cluster is deleted when the test ends.
func startMiniStackCluster(t *testing.T) string {
	t.Helper()
	base := os.Getenv("EMBEDDED_DSQL_MINISTACK_URL")
	if base == "" {
		base = "http://127.0.0.1:4566"
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()
	created, err := ministackCall(ctx, http.MethodPost, base+"/cluster", strings.NewReader(`{"deletionProtectionEnabled": false}`))
	require.NoError(t, err, "create a MiniStack DSQL cluster (is MiniStack running with SERVICES=dsql DSQL_STRICT=1?)")
	id, ok := created["identifier"].(string)
	require.True(t, ok, "cluster identifier in %v", created)
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
		defer cancel()
		_, err := ministackCall(ctx, http.MethodDelete, base+"/cluster/"+id, nil)
		require.NoError(t, err)
	})
	endpoint, ok := created["endpoint"].(string)
	require.True(t, ok, "cluster endpoint in %v", created)
	for {
		got, err := ministackCall(ctx, http.MethodGet, base+"/cluster/"+id, nil)
		require.NoError(t, err)
		if got["status"] == "ACTIVE" {
			break
		}
		select {
		case <-ctx.Done():
			t.Fatalf("cluster %s never became ACTIVE: %v", id, got)
		case <-time.After(500 * time.Millisecond):
		}
	}
	u, err := url.Parse("//" + endpoint)
	require.NoError(t, err)
	return fmt.Sprintf("postgres://admin:token@127.0.0.1:%s/postgres?sslmode=disable", u.Port())
}

type protocol string

const (
	simpleProtocol   protocol = "simple"
	extendedProtocol protocol = "extended"
)

// outcome renders a statement's result as "ok <tag> <rows>" or
// "error <sqlstate> <message>". Row values are left out for sys.jobs and
// wait_for_job ids, which differ between the two implementations.
func runStep(ctx context.Context, conn *pgconn.PgConn, proto protocol, sql string) (string, string) {
	var results []*pgconn.Result
	var err error
	if proto == simpleProtocol {
		results, err = conn.Exec(ctx, sql).ReadAll()
	} else {
		r := conn.ExecParams(ctx, sql, nil, nil, nil, nil).Read()
		results, err = []*pgconn.Result{r}, r.Err
	}
	if err != nil {
		if pgErr, ok := err.(*pgconn.PgError); ok {
			return fmt.Sprintf("error %s %s", pgErr.Code, pgErr.Message), ""
		}
		return "error " + err.Error(), ""
	}
	var parts []string
	first := ""
	for _, r := range results {
		part := "ok " + r.CommandTag.String()
		if len(r.Rows) > 0 && len(r.Rows[0]) > 0 {
			first = string(r.Rows[0][0])
		}
		if !strings.Contains(sql, "INDEX ASYNC") && !strings.Contains(sql, "TABLE ASYNC") {
			for _, row := range r.Rows {
				vals := make([]string, len(row))
				for i, v := range row {
					vals[i] = string(v)
				}
				part += " [" + strings.Join(vals, ",") + "]"
			}
		}
		parts = append(parts, part)
	}
	return strings.Join(parts, "; "), first
}

func runCase(t *testing.T, dsn string, tc parityCase, proto protocol, prefix string) []string {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	conns := make([]*pgconn.PgConn, 2)
	for i := range conns {
		c, err := pgconn.Connect(ctx, dsn)
		require.NoError(t, err)
		conns[i] = c
		t.Cleanup(func() { require.NoError(t, c.Close(context.Background())) })
	}
	var out []string
	last := ""
	for _, step := range tc.steps {
		conn := conns[0]
		if rest, ok := strings.CutPrefix(step, "2:"); ok {
			conn, step = conns[1], rest
		}
		sql := strings.ReplaceAll(strings.ReplaceAll(step, "{{t}}", prefix), "{{last}}", last)
		result, first := runStep(ctx, conn, proto, sql)
		if len(step) > 120 {
			step = step[:120] + "..."
		}
		out = append(out, step+" => "+result)
		last = first
	}
	return out
}

func TestParity(t *testing.T) {
	ministackDSN := startMiniStackCluster(t)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	db, err := Start(ctx, Options{})
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, db.Stop()) })

	for i, tc := range parityCases {
		for _, proto := range []protocol{simpleProtocol, extendedProtocol} {
			if tc.simpleOnly && proto == extendedProtocol {
				continue
			}
			t.Run(fmt.Sprintf("%s/%s", tc.name, proto), func(t *testing.T) {
				prefix := fmt.Sprintf("pc%d_%s", i, proto)
				want := runCase(t, ministackDSN, tc, proto, prefix)
				got := runCase(t, db.DSN(), tc, proto, prefix)
				require.Equal(t, want, got, "MiniStack (expected) vs embedded-dsql (actual)")
				if os.Getenv("EMBEDDED_DSQL_PARITY_VERBOSE") != "" {
					t.Log(strings.Join(got, "\n"))
				}
			})
		}
	}
}
